### ISSUE TITLE
Support balances for Orange.be

### ISSUE THREAD

**Issue by pietervdvn** [l-ray/gnome-shell-extension-prepaid#2]
Hi,

Would it be possible to add an option to login into an Orange.be account?

It would be fantastic if both the saldo, but also the resting data allowance would be shown.

**Comment by l-ray** [comment]
Hi Pieter, 
while I planned to have a look at data allowance over christmas (thanks for your request, now it will definitely be done)  - this will come. 
Harder to implement is the Orange.be account - as I neither speak French/Dutch nor have a login with those services to explore what needs to be done. 
If you want, have a look at the provider-classes existing and try to find your way yourself - it's actually not that hard. :+1:  https://github.com/l-ray/gnome-shell-extension-prepaid/tree/master/prepaid_balances%40l-ray.de/provider - am happy to support you here in case of any questions..

**Comment by pietervdvn** [comment]
I don't know enough of JS and webstuff to cook up the login; so I'll pass
on this one.


Met vriendelijke groeten,
Pieter Vander Vennet

2017-12-05 7:24 GMT+01:00 Lennart <notifications@github.com>:
